### ISSUE TITLE
Fix offline / connection lost

### ISSUE THREAD

**Issue by anbraten** [anbraten/obelix#13]
Sometimes the user is offline without any reason.

**Comment by anbraten** [comment]
@MaxAbbe
Could you help with some testing:
- try to login
- check if connection to backend stays alive (reload using F5, navigate via buttons)
- try to use obelix after min 30 minutes of inactivity again while keeping tab opened

**Comment by MaxAbbe** [comment]
I didn't check, if the app showed the offline status (had the browser minimized), but after around 15 minutes my user got logged out automatically.
